# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97167e877cb2d26d91062a689f83f95f0d27c0316b9ab999c5c17299b55523a22648519cd2983b29a361047ebf304776dcfbf2cd68bd743bc9705239005e943b

test:
  secret_key_base: 3f98b55e09a09f2db9b614d4011c3b65c6d097631ea5ef62f0dc5081020dbe0efd98d003400cd4575fabf036c54109e8070274b48614c639f8d85bf111b64885

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
